package com.news.entity;

// Generated 2017-2-15 19:28:48 by Hibernate Tools 4.0.0

import java.util.Date;

/**
 * NewsInfo generated by hbm2java
 */
public class NewsInfo implements java.io.Serializable {

	private Integer id;
	private Topic topic;
	private String title;
	private String author;
	private Date createDate;
	private String content;
	private String summary;

	public NewsInfo() {
	}

	public NewsInfo(Topic topic, String title, String author, Date createDate,
			String content) {
		this.topic = topic;
		this.title = title;
		this.author = author;
		this.createDate = createDate;
		this.content = content;
	}

	public NewsInfo(Topic topic, String title, String author, Date createDate,
			String content, String summary) {
		this.topic = topic;
		this.title = title;
		this.author = author;
		this.createDate = createDate;
		this.content = content;
		this.summary = summary;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Topic getTopic() {
		return this.topic;
	}

	public void setTopic(Topic topic) {
		this.topic = topic;
	}

	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	public String getAuthor() {
		return this.author;
	}

	public void setAuthor(String author) {
		this.author = author;
	}

	public Date getCreateDate() {
		return this.createDate;
	}

	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	public String getContent() {
		return this.content;
	}

	public void setContent(String content) {
		this.content = content;
	}

	public String getSummary() {
		return this.summary;
	}

	public void setSummary(String summary) {
		this.summary = summary;
	}

	@Override
	public String toString() {
		return "NewsInfo [id=" + id + ", topic=" + topic + ", title=" + title + ", author=" + author + ", createDate="
				+ createDate + ", content=" + content + ", summary=" + summary + "]";
	}
	
	

}
