package com.news.entity;

// Generated 2017-2-15 19:28:48 by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;

/**
 * Topic generated by hbm2java
 */
public class Topic implements java.io.Serializable {

	private Integer id;
	private String name;
	private Set newsInfos = new HashSet(0);

	public Topic() {
	}

	public Topic(String name) {
		this.name = name;
	}

	public Topic(String name, Set newsInfos) {
		this.name = name;
		this.newsInfos = newsInfos;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public Set getNewsInfos() {
		return this.newsInfos;
	}

	public void setNewsInfos(Set newsInfos) {
		this.newsInfos = newsInfos;
	}

}
